name: Build grpc on Power

on:
  workflow_call:
    inputs:
      release:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2  
      - uses: uraimo/run-on-arch-action@v2.2.0
        name: Install dependencies and build grpc
        id: build
        with:
          arch: ppc64le
          distro: ubuntu20.04
          
          # Create an artifacts directory
          setup: |
            mkdir -p "${PWD}/artifacts"
          
          # Mount the artifacts directory as /artifacts in the container
          dockerRunArgs: |
            --volume "${PWD}/artifacts:/artifacts"
            
      
          run: |            
            apt-get update -y
            apt-get install -y build-essential autoconf libtool pkg-config git software-properties-common curl 
            add-apt-repository ppa:deadsnakes/ppa -y
            apt-get install python3.9 python3-pip python3-dev libpython3.9-dev -y
            
            #Building grpc
            python3.9 -m pip install --upgrade pip
            echo "Building grpc ${{ inputs.release }}"
            pip install grpcio==${{ inputs.release }} 
            
            WHEEL_PATH=$(find /root/.cache/pip/wheels/ -name "grpcio*.whl")
            WHEEL_NAME=$(basename $(find /root/.cache/pip/wheels/ -name "grpcio*.whl"))
            cp $WHEEL_PATH /artifacts/$WHEEL_NAME           
                      
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ inputs.release }}
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          artifacts: ./artifacts/grpcio-${{ inputs.release }}-cp39-cp39-linux_ppc64le.whl
          name: ${{ inputs.release }}
          replacesArtifacts: true
          draft: false
          prerelease: false 